"use client";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthUserProvider } from "@/firebase/auth";
import Footer from "./components/footer";

import ShopContext from "./components/context";
import { useState, createContext } from "react";
const inter = Montserrat({ subsets: ["latin"] });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [shopNameContext, setShopNameContext] = useState("Shop Name");
  const [shopOwnerContext, setShopOwnerContext] = useState("Shop Owner");
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthUserProvider>
          <ShopContext.Provider
            value={{
              shopNameContext,
              setShopNameContext,
              shopOwnerContext,
              setShopOwnerContext,
            }}
          >
            <Navbar></Navbar>
            <main className="min-h-[calc(100vh_-_100px)] bg-[url('/main-bg.jpg')] bg-opacity-40 flex items-stretch">
              {children}
            </main>
            <Footer />
          </ShopContext.Provider>
        </AuthUserProvider>
      </body>
    </html>
  );
}
